ci: don't generate build checks instead iterate over commits
Signed-off-by: Florian Weßel <florianwessel@gmx.net>

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -20,8 +20,32 @@ jobs:
   Build_Desktop:
     uses: ./.github/workflows/pr-build.yml
 
+  Build_Desktop_Status_Check:
+    runs-on: ubuntu-latest
+    needs: [Build_Desktop]
+    if: always()
+    steps:
+      - name: Check Desktop Build Status
+        run: |
+          if [ "${{ needs.Build_Desktop.result }}" != "success" ]; then
+            echo "Desktop builds failed"
+            exit 1
+          fi
+
   Build_Android:
     uses: ./.github/workflows/pr-build-android.yml
+
+  Build_Android_Status_Check:
+    runs-on:  ubuntu-latest
+    needs: [Build_Android]
+    if:  always()
+    steps:
+      - name: Check Android Build Status
+        run: |
+          if [ "${{ needs.Build_Android. result }}" != "success" ]; then
+            echo "Android builds failed"
+            exit 1
+          fi
 
   # Linting_Include_What_You_Use:
   #   uses: ./.github/workflows/pr-iwyu.yml
